### ISSUE TITLE
Equalizer not working...

### ISSUE THREAD

**Issue by jpgilchrist** [ewall/meteor-foundation#13]
I cannot seem to get equalizer to work. I was hoping you could help.

    <template name="HomeLayout">
    <header>
        <div class="row fullWidth" data-equalizer="header">
            <div class="small-4 large-4 columns text-left" data-equalizer-watch="header">
                <i class="fa fa-2x fa-thumb-tack header-icon"></i>
            </div>
            <div class="small-4 large-4 columns text-center" data-equalizer-watch="header">
                Title
            </div>
            <div class="small-4 large-4 columns text-right" data-equalizer-watch="header">
                <i class="fa fa-2x fa-cog header-icon"></i>
            </div>
        </div>
    </header>
    ...
    </template>

**Comment by nanderson94** [comment]
Are you using any other packages? For example, iron:router? If so, look into #6

**Comment by jpgilchrist** [comment]
Sure am. I'll take a look at that issue.

**Comment by ewall** [comment]
@jpgilchrist -- How'd it go? Did that help?
