### ISSUE TITLE
Where to override default foundation styles?

### ISSUE THREAD

**Issue by ssoulless** [ewall/meteor-foundation#14]
Hi in Rails I used to modify apps.scss file that contains all the default styles of foundaiton, but here I do not know where to modify default styles of meteor

**Comment by ewall** [comment]
This is probably not the Meteor package for you — it does not include any if the SCSS source files. As I hoped is clear in the readme, this package just includes the default CSS & JS so it's mostly used for quick dev/test kind of apps (or people who don't plan on changing any of the styles). So I suspect you're going to want to fetch the Foundation SCSS yourself or try one of the other packages that include them such as matthew:foundation5-sass.
